# Generated by Django 5.1.6 on 2025-03-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_collectionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrequest',
            name='accepted',
        ),
    ]
