# Generated by Django 5.1.6 on 2025-03-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_posts/'),
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
