# Generated by Django 5.2 on 2025-04-11 17:38

import vehicles.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=vehicles.storage_backends.MediaStorage(), upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=vehicles.storage_backends.MediaStorage(), upload_to='vehicle_posts/'),
        ),
    ]
