# Generated by Django 5.1.6 on 2025-04-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehiclerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='status',
        ),
    ]
